"""Common interface for all answer-generation providers."""

from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass(slots=True)
class GenerationResult:
    """Text generated by one configured provider."""

    text: str
    provider: str


class LLMProvider(ABC):
    """Abstract provider implemented by local, Groq and retrieval modes."""

    name = "base"

    @abstractmethod
    async def generate(
        self, prompt: str, context_chunks: list[str]
    ) -> GenerationResult:
        """Generate or assemble an answer from grounded context."""
